### PR TITLE
Feature/deploy to netlify

### PR DESCRIPTION
**Pull request by abisuq**
deployed site as example: https://master--amazing-horse-5c036c.netlify.app/
solved: #141

### CODE REVIEW

**Comment by zu1k** [comment]
> When you assign an [HTTP status code](https://docs.netlify.com/routing/redirects/redirect-options/#http-status-codes) of 200 to a redirect rule, it becomes a rewrite.

https://docs.netlify.com/routing/redirects/rewrites-proxies/

**Comment by zu1k** [comment]
And use `:splat`

https://docs.netlify.com/routing/redirects/rewrites-proxies/#proxy-to-another-service

**Comment by abisuq** [comment]
https://master--amazing-horse-5c036c.netlify.app/

**Comment by zu1k** [comment]
It works, thanks!

**Pull request merged**
